### PR TITLE
Check that defaultValue is a function or primitive type, fixes #32

### LINKED ISSUE #32: Referential `defaultValue`s
Often people forget (or don't know) that you must use either a primitive value or a function to return any object/array type for `property.defaultValue`, eg:

```js
{ a: { type: Array, defaultValue: [] }
, b: { type: Object, defaultValue: {} }
}
```

```js
var obj = schemata.makeDefault()
obj.a.push('something')
obj.b.oops = 'this is bad'

var obj2 = schemata.makeDefault()
obj2.a.length //-> 1
obj2.b.oops //-> 'this is bad'
```

This happens often enough that I think schemata should either **cope** *or* **complain**.

So my suggested options are:

1. Throw an exception if `defaultValue` is not a) a function or b) a primitive type (number, string, null, undefined etc.)
2. Accept any input and deep clone any array/object types so that.

@serby, @microadam, @domharrington what do you think we should do?

### PR DESCRIPTION
**Pull request by bengourley**
This checks in the constructor that all of the `defaultValue`s on the schema properties are either 'primitive' or functions.

The only case where this won't help is in some of our applications I've seen the internal `schemata.schema` updated. In that case the check has already happened, so it would be possible to get the schema into an invalid state. But that is no worse than the current situation.

### CODE REVIEW

File: schemata.js [hunk 1]
```diff
@@ -23,6 +24,12 @@ function createSchemata(schema) {
 
 function Schemata(schema) {
   this.schema = schema || {}
+  Object.keys(this.schema).forEach(function (k) {
+    if (!schema[k].defaultValue) return
+    if (typeof schema[k].defaultValue === 'function') return
+    if (isPrimitive(schema[k].defaultValue)) return
+    throw new Error('Schema property "' + k + '" must be either a primitive value or a function')
```
Comment (serby) [inline schemata.js]: Message doesn't sound quite right.

Perhaps
`The default value for the Schema property "' + k + '" must be either a primitive value or a function`

**Comment by bengourley** [comment]
@serby updated the error message based on your feedback

**Comment by serby** [comment]
It's going to have to be a version bump I think.
